# DAFTAR-ML Hyperparameter Search Space Configuration
# 
# This file defines the hyperparameter search spaces for all models in DAFTAR-ML.
# Edit this file to customize the hyperparameter optimization process.

# Random Forest hyperparameters
random_forest:
  n_estimators:    # Number of trees in the forest
    min: 100
    max: 1000
  max_depth:       # Maximum depth of trees
    min: 3
    max: 30
  min_samples_leaf:   # Minimum samples required in a leaf node
    min: 1
    max: 10
  max_features:       # Fraction of features to consider for each split
    min: 0.1
    max: 0.8
  min_samples_split:  # Minimum samples required to split a node
    min: 2
    max: 10
  criterion:          # Function to measure the quality of a split
    classification: ["gini", "entropy"]
    regression: ["squared_error", "absolute_error"]
  # max_leaf_nodes:    # Grow trees with max_leaf_nodes in best-first fashion
  #   min: 10
  #   max: 1000
  # min_impurity_decrease:  # Minimum impurity decrease required to make a split
  #   min: 0.0
  #   max: 0.1

# XGBoost hyperparameters
xgboost:
  n_estimators:    # Number of boosting rounds
    min: 100
    max: 1000
  max_depth:       # Maximum depth of trees
    min: 3
    max: 20
  learning_rate:   # Step size shrinkage used to prevent overfitting
    min: 0.01
    max: 0.4
  subsample:       # Subsample ratio of training instances
    min: 0.5
    max: 1.0
  colsample_bytree:  # Subsample ratio of columns when constructing each tree
    min: 0.5
    max: 1.0
  min_child_weight:  # Minimum sum of instance weight needed in a child
    min: 1
    max: 10
  # gamma:           # Minimum loss reduction required to make a split (regularization)
  #   min: 0
  #   max: 0.3
  # reg_alpha:       # L1 regularization term on weights
  #   min: 0
  #   max: 1.0
  # reg_lambda:      # L2 regularization term on weights
  #   min: 0
  #   max: 1.0